title: ABHIRAJ KUMAR SINGH # your name (or website title) here
logo: "/images/logooo.PNG?raw=true" # your photo (or logo) here
description: Undergrad in Electronics & Communication with AI & Data Science at Vel Tech University, Chennai.> # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Undergrad in Electronics & Communication with AI & Data Science at Vel Tech University, Chennai
  <br><br>
  Data Analyst | AI Researcher | NCC Cadet
  <br><br>
  <a href="https://www.linkedin.com/in/abhirajsingh05/"> LinkedIn Profile</a>
  <br>
  <a href="https://www.instagram.com/its_kumarabhi/"> Instagram</a>
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
